spring:
  h2:
    console:
      enabled: true
      path: /h2console

spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bootexample;MODE=MySQL

server:
  port: 8090
  context-path: /product-catalogue

#todo: make sure to always enable security in production
security:
  basic:
    enabled: false

#management endpoints on a separate port
management:
  port: 8091
  security:
    enabled: false # management port is internal only. no need to secure it.


spring.jpa:
    hibernate.ddl-auto: create-drop

