spring:
  h2:
    console:
      enabled: true
      path: /h2console
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bootexample;MODE=MySQL
  jpa:
    hibernate.ddl-auto: create-drop

server:
  port: 8090
  context-path: /product-catalogue

security:
  basic:
    enabled: false

management:
  port: 8091
  security:
    enabled: false
